Feature/insults module
dmartinezgamboa/roastme-bot pull request #4
Opened 2021-10-21 09:18 UTC by dmartinezgamboa

Refactor client.py:

1. It now determines if message is a valid command.
2. Sends message to separate insults.py module in function call.
3. insults.py returns insult for client.py to send.

This should allow for easy creation of more insult functions in separate insults.py module, and client.py to be more cohesive.

2021-10-22 22:55 UTC, bryanterichardson commented
Hmmm in this case I think you can do all of this in one commit.

2021-10-22 22:56 UTC, bryanterichardson commented on roastme/insults.py
> +data = load_json_data()
I still prefer the data where we had it. Not a fan of a global variable for this. Would ask that you refactor without movie the data object from the class

2021-10-22 22:56 UTC, bryanterichardson commented on roastme/client.py
> +import re
I showed you the `.mentions` property so this regex module and logic is unnecessary

2021-10-22 22:57 UTC, bryanterichardson commented on roastme/client.py
> +            return True
Method unnecessary I believe

2021-10-22 22:58 UTC, bryanterichardson commented on roastme/client.py
> +        message_array = message_obj.content.split()
again use mentions

2021-10-22 22:58 UTC, bryanterichardson commented on roastme/client.py
> +        return self._data
In python, we end all files with a new line. Idk if that applies everywhere but def in python. You removed that new line at the end of the file in your commit

2021-10-22 23:01 UTC, bryanterichardson commented on roastme/insults.py
> +def load_json_data():
this method is a dupe and has an incorrect signature. I already refactored this to take a path here https://github.com/dmartinezgamboa/roastme-bot/blob/main/roastme/main.py#L6-L10

Your change is reverting my refactor. Be sure to rebase and start with clean changes so that you arent working with old files.

2021-10-22 23:02 UTC, bryanterichardson commented on roastme/insults.py
> +    return roast_tagged_user(user)
Based on what you are doing, I dont think the roast should take a command. It should instead take a user! Because you are roasting a user not a command. Line 13 becomes unnecessary and thus this function might be unnecessary. We may only need `roast_tagged_user`

2021-10-22 23:02 UTC, bryanterichardson commented on roastme/insults.py
> +        return user + " is " + adjective
New line at the end of the file

2021-10-22 23:03 UTC, bryanterichardson requested changes
The intent is there. But some cleaning up to do before we should merge this. Let me know if you want to pair

2021-10-23 00:00 UTC, dmartinezgamboa commented on roastme/insults.py
> +data = load_json_data()
If the data is loaded with the class would we send the data along with the tagged_user to the insults module as arguments? 
I was wondering if that step was unnecessary. Since the insults module just returns a str with the roast, why not let the insults module load the data?

2021-10-23 00:01 UTC, dmartinezgamboa commented on roastme/client.py
> +import re
Yeah refactor using .mentions is a must.

2021-10-23 00:01 UTC, dmartinezgamboa commented on roastme/client.py
> +            return True
Once .mentions is implemented this is an easy refactor.

2021-10-23 00:06 UTC, dmartinezgamboa commented on roastme/insults.py
> +    return roast_tagged_user(user)
This is one I'd like to discuss more when we pair. 
I agree, for now, insults module only needs a user. I was attempting to future proof with a command object, since we plan to implement more logic to allow bot to enter voice and play audio. I thought it would be useful to have a command object for future voice channel logic within the client.

2021-10-30 00:23 UTC, bryanterichardson approved these changes
This is beautiful. BEFORE YOU MERGE CLEAN UP YOUR COMMITS. But this is goooood

2021-11-04 01:54 UTC, merged